#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, linting, testing and translating Odyn 2.0 before committing'

# Check Prettier standards
npm run format:check > /dev/null && echo '\033[0;32m✔ Prettier\033[0m' || (
  echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
          Prettier Check Failed. Run yarn format, add changes and try to commit again.';
  false;
)

# Check ESLint Standards
npm run lint || (
  echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
          ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
  false;
)

# Commit if we passed all the tests
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅';
